// Edit agency copy here; run `npm run content:build` to update the preserved site.
export const agency = {
  name: 'Optitech', url: 'https://optitech-uk.vercel.app',
  headline: 'Digital Systems Built to Grow Your Business.',
  positioning: 'Web Development, Digital Marketing & Automation for UK Businesses.',
  description: 'We design high-performing websites, help businesses get discovered through search and paid media, and automate the systems that turn leads into customers.',
  platforms: ['WordPress','Shopify','Google','Meta','Stripe','PayPal','React','Next.js','Vercel','WooCommerce'],
  pricing: ['Business websites from £750','E-commerce from £1,200','Custom web applications: tailored quote','SEO from £450/month','Paid media from £500/month; advertising spend excluded','Growth partnerships from £950/month','CRM & automation from £350 setup'],
  process: ['Discover','Strategy','Design & Build','Launch','Grow','Report & Optimise'],
  faqs: [
    ['How much does a website cost?','Business websites start at £750; e-commerce starts at £1,200. Your proposal sets out the scope and final price.'],
    ['How long does a website project take?','Timing depends on scope, content and integrations. We agree a delivery plan before work starts.'],
    ['Do you work outside London?','Yes. We support businesses across London and the UK through remote delivery and clear communication.'],
    ['Do you provide ongoing support?','Yes. Maintenance, updates, performance checks and ongoing optimisation can be included in your agreement.'],
    ['Can you manage SEO after launch?','Yes. Technical SEO, local search, content and reporting can form an ongoing growth plan.'],
    ['Do you manage Google Ads and Meta Ads?','Yes. Campaign management, landing pages and conversion tracking work together. Advertising spend is separate.'],
    ['Can you integrate CRM and follow-ups?','Yes. We can connect forms, CRM, email and messaging workflows around your business needs.'],
    ['Do I own my website and accounts?','Ownership, access and any third-party licences are clearly set out in your agreement.'],
    ['Can you improve an existing website?','Yes. We can review your site and recommend practical improvements or a redesign.'],
    ['Do you build Shopify and WooCommerce stores?','Yes. We support store development, product setup, payments, email automation and maintenance.'],
  ],
};
export const capabilities = [
  'Business Websites','WordPress Development','Shopify Development','E-commerce Development','React Development','Next.js Development','Landing Pages','Website Redesign','Website Maintenance','Speed Optimisation','API Integrations',
  'SEO','Local SEO','Google Business Profile','Technical SEO','On-page SEO','Content Strategy','E-commerce SEO','Keyword Research','SEO Audits','AI Search Optimisation',
  'Google Ads','Meta Ads','PPC Management','Retargeting','Landing Page Optimisation','Conversion Tracking','Analytics','Conversion Optimisation',
  'CRM Integration','Lead Capture','Email Follow-up','WhatsApp Automation','Messenger Automation','AI Chatbots','Appointment Automation','Workflow Automation','Reporting Dashboards','AI Business Tools',
  'WooCommerce','Product Setup','Payment Gateways','Stripe','PayPal','Store Maintenance',
  ...agency.process.map(s=>'How we work: '+s), ...agency.pricing, ...agency.faqs.map(([q])=>q),
];
export const replacements = {
 'Pensatori Irrazionali':'Optitech', 'PENSATORI IRRAZIONALI':'OPTITECH','By Pensatori Irrazionali':'By Optitech · Demo reference','Diagram By Pensatori Irrazionali':'Digital growth with Optitech',
 'Atelier':'Optitech','A creative house based in Europe, operating':'Digital Systems Built to Grow Your Business.',
 'worldwide. We shape experiences where depth,':'Web Development, Digital Marketing & Automation',
 'elegance, and essence are felt, not explained.':'for UK Businesses. Build, attract, convert and automate.',
 'We help visionary brands flourish by crafting digital experiences that let audiences feel the depth, elegance, and essence of their products.':agency.description,
 'We help visionary brands flourish':'We design high-performing websites,',
 'by crafting digital experiences that let':'help businesses get found through search and ads,',
 'audiences feel the depth, elegance, and':'and automate the systems that turn',
 'essence of their products.':'leads into customers across London and the UK.',
 'Trusted by':'Platforms','From emerging ventures to global names, we build':'Platforms & Technologies We Work With.',
 'work designed to feel sharper, deeper and':'WordPress, Shopify, Google, Meta, Stripe, PayPal,',
 'more memorable.':'React, Next.js and Vercel. Chosen for your goals.',
 'Works':'Selected Work','Disciplines':'Services','Clients':'Solutions','Universe':'Insights',
 'Branding':'SEO','Brand':'Search','Identities':'Visibility','Brand Identities':'Search Visibility',
 'Logo':'Local SEO','Wordmark & monogram versions':'Google Business Profile & local visibility',
 'Systems':'Technical SEO','Font families with licensing':'Audits, site structure & speed',
 'Psychology':'Search Intent','Cultural & emotional meaning':'Keyword research & content strategy',
 'Visual':'On-page SEO','Shapes, illustrations & texturing':'Content, headings & internal links',
 'Expression':'Organic Growth','Social media kits, print & UI elements':'E-commerce SEO & AI search visibility',
 'We don’t do generic design. Our creative solutions make brands stand out, improve user experience, and boost revenue.':'Not getting found? Get discovered by people already searching for what you offer. SEO and local growth from £450/month.',
 'Websites':'Web Development','Web Development':'Web Development','Web':'Web','Development':'Development',
 'Frontend':'Websites','React / Next.js / Three.JS / WebGL builds':'Business, WordPress, React & Next.js websites',
 'Backend':'Integrations','APIs, databases & scalable infrastructure':'APIs, databases & third-party integrations',
 'E-Commerce':'E-commerce','Shopify integrations & payments':'Shopify, WooCommerce, Stripe & PayPal',
 'Speed optimization, structure & ranking':'Landing pages, technical SEO & performance',
 'Hosting, updates & ongoing support':'Redesigns, updates & ongoing UK support',
 'We design and develop websites that are visually striking, intuitive, and built for the modern web.':'Visitors but no enquiries? Fast, conversion-focused websites built around real business goals. Business sites from £750; e-commerce from £1,200.',
 'Gaming':'Automation','Game':'CRM','Design':'Automation','Game Design':'CRM Automation',
 'Mechanics':'Lead Capture','Core gameplay systems & logic':'Forms, CRM integration & lead routing',
 'Level Design':'Follow-up','Maps, environments & player flow':'Email, WhatsApp & Messenger automation',
 'UI/UX':'AI Tools','HUD, menus & interaction design':'AI chatbots & business tools',
 'Visuals':'Appointments','Characters, props & world elements':'Booking workflows & reminders',
 'Integration':'Reporting','Economy, progression & features':'Dashboards & workflow automation',
 'We design immersive gaming experiences, crafting visuals, environments, and systems that bring digital worlds to life.':'Leads going cold? Capture, organise and follow up with leads automatically. CRM and automation from £350 setup; scope agreed in your proposal.',
 'Production':'Paid Media','Video':'Paid','Video Production':'Paid Media Growth',
 'Concept':'Strategy','Creative direction, storytelling & scripting':'Google Ads, Meta Ads & PPC planning',
 'Pre-Production':'Tracking','Planning, casting & locations':'Analytics & conversion measurement',
 'Filming, cinematography & direction':'Campaign setup, targeting & creative',
 'Post-Production':'Optimisation','Editing, color grading & sound':'Retargeting & landing page optimisation',
 'Distribution':'Conversion','Formats, optimization & rollout':'Testing, reporting & next priorities',
 'We produce high-end visual content, combining storytelling, direction, and execution to craft cinematic experiences.':'Advertising not delivering? Turn advertising spend into measurable business opportunities. Management from £500/month; advertising spend excluded.',
 'Los Angeles':'UK Businesses','Tokyo':'Remote Delivery','From':'For','To':'Across',
 'Dubai, UAE':'UK-focused delivery','Building A1, Dubai Digital Park':'Remote service · ongoing support',
 'Emails':'Enquiries','hello@pensatori-irrazionali.com':'Book a Free Strategy Call','jobs@pensatori-irrazionali.com':'Tell Us About Your Project',
 'Copy our email':'Copy contact link','Email copied':'Contact link copied','LinkedIn':'Strategy Call','Instagram':'Project Enquiry','X / Twitter':'Support',
 'Contact Us':'Book a Strategy Call','Start a project':'Book a Free Strategy Call','Drop a quick word':'Tell Us About Your Project',
 'Aeva':'Optitech','All Copyrights Reserved by':'All rights reserved by','Creative studio':'Digital solutions agency',
 'Metaverse':'Local SEO','Content':'SEO','Games':'Google Ads','Brands':'Meta Ads','Animations':'E-commerce','3D Models':'CRM','AR & VR':'AI & Automation',
 'Under €10k':'Under £1,000','€10k - €25k':'£1,000 - £2,500','€25k - €50k':'£2,500 - £5,000','€50k - €100k':'£5,000 - £10,000','€100k - €250k':'£10,000 - £25,000','Unlimited':'Discuss a tailored scope',
 '3D / Animation':'E-commerce','YouTube':'Ongoing Support','Website':'Website','Choose why you are contacting us':'Let’s plan your next step',
 'What brings you here today?':'How can we help your business?','Who is the mind behind it?':'What is your name?',
 'Which company are you with?':'Which business are you contacting us about?','Company or studio':'Your business name',
 'Where do we come into play?':'Which services would help your business?','What budget range are we playing in?':'What budget range do you have in mind?',
 'Give us the full picture of the project.':'Tell us about your business goals.',
 'We’ll get back to you in 1-3 days.':'Your enquiry needs a configured delivery service.',
 'Your project inquiry did not send this time.':'Your project enquiry did not send this time.',
 'Work Hours':'Reference scope','People Worked':'Reference team','Director of Project':'Reference source','Published by':'Presented as a demo by',
 'Project Details':'Demo Details','(About it)':'(Demo reference)','(Examples & Work)':'(Reference media)',
 'Imagery':'Let’s Grow','Learn More':'Explore Services',
 'Contact':'Contact','Contact us':'Book a Free Strategy Call',
 'Pensatori Irrazionali operates this website at pensatori-irrazionali.com. Our listed contact location is Building A1, Dubai Digital Park, Dubai, UAE.':'Optitech provides digital services for UK businesses through remote delivery. This website does not claim a physical London office.',
 'For privacy questions, requests, or complaints, contact us at hello@pensatori-irrazionali.com.':'Use the contact page for project and privacy enquiries. Message delivery is not yet configured on this reference site; do not submit sensitive information.',
 'Production website analytics and performance information collected through Cloudflare Web Analytics, such as page views, referrers, browser and device information, approximate location, and Core Web Vitals or similar performance metrics.':'The original analytics beacon is disabled in this project. Hosting infrastructure may record technical requests needed to serve and protect the website.',
 'Cloudflare Web Analytics is used on the production website to measure traffic and performance without using cookies or localStorage for usage metrics.':'Cloudflare Web Analytics is disabled in this project.',
 'You may also have the right to complain to a data protection authority. To make a request, email hello@pensatori-irrazionali.com. We may need to verify your identity and may retain information where the law allows or requires us to do so.':'You can raise a privacy question through the contact page once message delivery is configured. You may also contact the relevant data protection authority.',
 'To understand production website traffic, page performance, and visitor experience through privacy-focused analytics.':'To maintain page performance and visitor experience. The original analytics beacon is disabled.',
 'OPTION SET 1':'GROWTH STEP 1','SYSTEM / STUDIO CORE':'ATTRACT / SEO + PAID MEDIA','DESIGN / TECHNOLOGY / CULTURE':'WEBSITE / VISIBILITY / LEADS','POST-DEPLOYMENT / PRE-STABILITY':'BUILT FOR UK BUSINESSES',
 'Recursive Diagram of One Studio System':'Everything works better when it works together.',
 '(left to right) for speculative practice,':'One team plans your digital growth system,',
 'becoming a container for identity, technology, and form':'bringing development, marketing and automation together',
 'as an active ecology.':'with clear communication and ongoing support.',
 'WIT BWIT FNOS SNOS':'BUILD ATTRACT CONVERT AUTOMATE','IDENTITY / MODULE 01':'ATTRACT / MODULE 01',
 'ID: STUDIO–ID–A01':'SEO / LOCAL SEARCH / PPC','A container for intention.':'Get found by the right people.',
 'Form emerges before explanation.':'SEO and conversion start during the build.',
 'Identity stabilizes only through repetition.':'Track visibility, traffic and qualified enquiries.',
 'OPTION SET 2':'GROWTH STEP 2','PROCESS / LOADING STATE':'CONVERT / WEBSITE + LANDING PAGES',
 'SYSTEM STATUS: INITIALIZING':'HOW WE WORK: DISCOVER → STRATEGY','MODE: SPECULATIVE':'DESIGN & BUILD → LAUNCH → GROW → REPORT',
 'Each module operates independently,':'We understand your business, audience and goals,',
 'yet remains influenced by adjacent structures.':'then plan, build and launch the right system.',
 'Failure, delay, and recursion':'Tracking and SEO foundations are configured,',
 'are treated as generative forces.':'then reviewed and improved with useful reporting.',
 'SYSTEMS / MODULE 02':'CONVERT / MODULE 02','ID: SYS–CORE–B07':'BUSINESS / E-COMMERCE / CUSTOM',
 'Systems are not designed.':agency.pricing[0],'They are discovered through constraints.':agency.pricing[1],
 'Failure refines the architecture.':agency.pricing[2],
 'OPTION SET 3':'GROWTH STEP 3','FORM / IDENTITY':'CAPTURE / FORMS + CRM',
 'IDENTITY / FORM / SIGNAL - ASSEMBLED OVER TIME':'LEAD CAPTURE / ROUTING / OWNERSHIP','POST-INTERFACE CONDITION':'ONE POINT OF CONTACT',
 'Form is treated as a consequence':'Your website should do more than look good.',
 'of accumulated decisions and constraints.':'Capture leads and connect your business tools.',
 'No single element retains autonomy.':'Ownership and access are agreed from the start.',
 'Stability is temporary.':'Business goals guide technology decisions.',
 'IDENTITY / MODULE 03':'CAPTURE / MODULE 03','ID: UI–THRESHOLD–C12':'CRM / INTEGRATIONS / DATA',
 'An interface is a negotiation':agency.pricing[6],'between machine logic':'Connect an existing website or build anew.',
 'and human instinct.':'A clear scope and proposal before work starts.',
 'OPTION SET 4':'GROWTH STEP 4','INTERFACE / MEDIATION':'FOLLOW UP / EMAIL + AUTOMATION',
 'INTERFACE / EMBODIMENT - ACTIVE FEEDBACK LOOP':'EMAIL / WHATSAPP / MESSENGER / AI','CALIBRATION IN PROGRESS':'AUTOMATION BUILT IN',
 'Diagram of Mediation Between Human and Machine':'More than a web agency.',
 'where interfaces function as negotiation zones':'One team for your complete digital growth system,',
 'rather than solutions.':'from enquiry to follow-up and ongoing improvement.',
 'NARRATIVE / MODULE 04':'FOLLOW UP / MODULE 04','ID: NAR–SEQ–D09':'TRIGGERS / WORKFLOWS / FOLLOW-UP',
 'Narrative is not linear.':'Follow-up continues after a form submission.',
 'It folds, repeats, and leaks':'CRM, email and appointments stay connected.',
 'across mediums.':'Workflows built around your business needs.',
 'OPTION SET 5':'GROWTH STEP 5','ARCHIVE / MEMORY':'MEASURE / ANALYTICS + REPORTING',
 'ARCHIVE / SYSTEM MEMORY':'KNOW WHAT’S WORKING','READ-WRITE STATE, NON-FINAL RECORD':'TRAFFIC / LEADS / CONVERSIONS / NEXT PRIORITIES',
 'FORM / MODULE 05':'MEASURE / MODULE 05','ID: FORM–FIELD–E03':'TRACK / REVIEW / OPTIMISE',
 'Form is a consequence,':agency.pricing[3],'not a decision.':agency.pricing[4],'Shape follows pressure.':agency.pricing[5],
};
