export const siteUrl = 'https://optitech-uk.vercel.app';
// Shared content for pages, homepage rows and server-side enquiry validation.
const pack = (id, name, price, timeline, description, ideal, features) => ({ id, name, price, timeline, description, ideal, features });
const faq = (question, answer) => ({ question, answer });
export const services = [
  {
    slug: 'web-development', title: 'Web Design & Development', category: 'Design & Build', headline: 'Professional Websites Built to Grow Your Business',
    description: 'From high-converting landing pages to fully customised business websites, we design and develop fast, responsive digital experiences tailored to your goals.', startingPrice: 'From £350',
    offers: ['Campaign landing pages', 'Small business websites', 'WordPress websites', 'Custom-coded websites'],
    included: ['Responsive design for mobile, tablet and desktop', 'Contact and lead enquiry forms', 'Basic on-page and technical SEO foundations', 'Analytics integration and performance optimisation', 'Deployment support and a practical handover'],
    packages: [
      pack('landing-page', 'Landing Page', '£350–£650', '3–7 working days', 'One focused page built around a clear customer action.', 'Campaigns, product launches and new businesses.', ['Single-page responsive design', 'Conversion-focused layout', 'Contact or lead generation form', 'Basic on-page SEO', 'Mobile optimisation', 'Analytics integration', 'Deployment support']),
      pack('small-business', 'Small Business Website', '£799–£1,299', '7–14 working days', 'A professional home for your business, services and enquiries.', 'Local businesses and small companies.', ['Up to 5 pages', 'Customised responsive layout', 'Home, About, Services, Contact and one additional page', 'Lead enquiry form', 'Basic technical and on-page SEO', 'Analytics setup', 'Speed optimisation', 'Deployment and handover']),
      pack('wordpress', 'WordPress Business Website', '£899–£1,499', '10–20 working days', 'A flexible website with content you can manage yourself.', 'Businesses requiring editable content and ongoing updates.', ['WordPress CMS', 'Up to 5 standard pages', 'Customised professional design', 'Content management', 'Contact forms', 'Essential SEO setup', 'Responsive design', 'Security and performance configuration', 'Admin handover']),
      pack('custom-coded', 'Custom-Coded Website', 'From £1,499', '2–4 weeks', 'A bespoke website tailored to your interface and integration needs.', 'Businesses requiring more flexible and tailored websites.', ['React / Next.js or suitable technologies', 'Bespoke interface development', 'Responsive layouts', 'Performance optimisation', 'API integration where scoped', 'Technical SEO foundations', 'Deployment and documentation']),
    ],
    note: 'Prices and timelines are estimates and depend on content readiness, integrations, design complexity and final project requirements. Hosting, domain registration, paid plugins and ongoing maintenance may be charged separately.',
    extraNote: 'Complex web applications are quoted separately under Custom Software Development.',
    comparison: { caption: 'Choose the right website', headings: ['Website type', 'Best suited to', 'Content & flexibility'], rows: [
      ['Landing Page', 'One campaign, offer or launch', 'A single page with a focused enquiry action.'], ['Small Business Website', 'Introducing a business and its services', 'Up to five pages; content updates scoped separately.'],
      ['WordPress Website', 'Regular content editing', 'Up to five standard pages with a content management system.'], ['Custom-Coded Website', 'A tailored interface or scoped integrations', 'Bespoke code; editing tools and APIs agreed during discovery.'],
    ] },
    faqs: [faq('Which website package should I choose?', 'A landing page suits one campaign. A small business website covers a broader business presence. Choose WordPress for editable content, or custom code for a tailored interface. We help define the scope before quoting.'), faq('Do I need to provide the content?', 'Please provide your logo, approved copy and images. Content readiness affects delivery. Copywriting, photography and content preparation can be discussed separately.'), faq('Are hosting and a domain included?', 'Hosting, domains and paid plugins may be charged separately. Your quotation specifies what is included and any recurring costs.'), faq('Can I update the website myself?', 'WordPress includes content management and an admin handover. Editing tools for a custom-coded website need to be agreed in the scope.'), faq('Can you build an application as well?', 'User accounts, complex workflows and substantial backend functionality are scoped under Custom Software Development, rather than a standard website package.')],
  },
  {
    slug: 'ecommerce', title: 'E-commerce Development', category: 'Online Stores', headline: 'Online Stores Designed to Sell', description: 'Make shopping straightforward with a responsive online store, clear product journeys and the integrations your business needs.', startingPrice: 'From £1,299',
    offers: ['Shopify stores', 'WooCommerce stores', 'Advanced e-commerce solutions'], included: ['Store design and setup', 'Product and collection configuration', 'Payment gateway integration', 'Shipping configuration', 'Mobile optimisation', 'SEO foundations', 'Conversion-focused design', 'Essential store integrations'],
    packages: [pack('shopify', 'Shopify Store Development', '£1,299–£2,499', '2–4 weeks', 'A store built on Shopify with a clear customer journey.', 'Businesses looking for a managed e-commerce platform.', ['Store design and setup', 'Agreed products and collections', 'Payment and shipping configuration', 'Mobile optimisation and SEO foundations', 'Essential integrations and handover']), pack('woocommerce', 'WooCommerce Store Development', '£1,299–£2,499', '2–4 weeks', 'An online store connected to your WordPress content.', 'Businesses seeking a WordPress-based shop.', ['WooCommerce setup and store design', 'Agreed products and collections', 'Payment and shipping configuration', 'Mobile optimisation and SEO foundations', 'Essential integrations and admin handover']), pack('advanced', 'Advanced E-commerce Solution', 'Custom Quote', 'Based on scope', 'A tailored store for more involved operations and integrations.', 'Businesses with complex catalogues or bespoke requirements.', ['Requirements and platform planning', 'Tailored store functionality', 'Scoped inventory and system integrations', 'Customer journey review', 'Testing, deployment and documentation'])],
    note: 'Prices and delivery estimates depend on catalogue size, content readiness and integrations. Platform subscriptions, transaction fees, product data preparation and paid apps are separate unless included in the quotation.',
    faqs: [faq('Should I choose Shopify or WooCommerce?', 'Shopify offers a managed platform with a subscription. WooCommerce runs on WordPress and needs hosting and maintenance. We review your catalogue, budget and requirements before recommending a platform.'), faq('How many products are included?', 'Product and collection quantities are agreed in your quotation. Preparing descriptions, photographs and catalogue data is separate unless included.'), faq('Are payment fees included?', 'Platform subscriptions, payment provider fees, transaction fees and paid apps are separate unless stated in the quotation.'), faq('Can you connect inventory or other business systems?', 'Where supported, integrations are scoped before quoting. Complex requirements may need an advanced solution.'), faq('When does the delivery estimate start?', 'The estimate assumes an agreed scope, platform access and ready product data. Third-party approvals can affect launch timing.')],
  },
  {
    slug: 'seo', title: 'SEO & Local SEO', category: 'Organic Growth', headline: 'Improve Your Visibility. Attract More Relevant Customers.', description: 'Build stronger search foundations with technical improvements, relevant content and a clear plan for your local or wider market.', startingPrice: 'From £350/month',
    offers: ['Local SEO', 'Technical and on-page SEO', 'Content planning', 'Search performance reporting'], included: ['SEO audit', 'Keyword research', 'Competitor analysis', 'Technical SEO', 'On-page optimisation', 'Local SEO', 'Content recommendations', 'Search performance tracking', 'Monthly reporting'],
    packages: [pack('local-starter', 'Local SEO Starter', '£350/month', 'Ongoing monthly service', 'Focus on local search foundations and priority improvements.', 'Local businesses targeting their service area.', ['Initial audit and local keyword research', 'Priority on-page recommendations', 'Local SEO improvements within agreed scope', 'Search performance tracking', 'Monthly reporting']), pack('growth', 'SEO Growth', '£450–£600/month', 'Ongoing monthly service', 'A broader programme of technical, on-page and content improvements.', 'Businesses developing their organic search presence.', ['SEO audit and competitor analysis', 'Keyword research and page planning', 'Technical and on-page optimisation', 'Content recommendations', 'Search performance tracking and monthly reporting']), pack('advanced', 'Advanced SEO', 'Custom Quote', 'Programme agreed after audit', 'A scoped programme for larger or more complex websites.', 'Businesses with extensive content or technical requirements.', ['Detailed technical discovery', 'Custom keyword and content strategy', 'Prioritised implementation roadmap', 'Agreed reporting and review schedule'])],
    note: 'SEO is an ongoing process. Rankings, traffic growth and specific results are not guaranteed. Monthly scope and implementation priorities are agreed before work starts. Google Business Profile setup and management are available as a separate service.',
    faqs: [faq('How quickly will SEO make a difference?', 'Search improvements take time and depend on your website, competition and implementation. We review agreed metrics without promising a fixed date for results.'), faq('Can you guarantee a first-page ranking?', 'No. Search engines control rankings. We focus on sound technical foundations, relevant content and measurable work.'), faq('Is Google Business Profile included?', 'Google Business Profile has its own service page and packages. Any overlap with local SEO is identified in your quotation.'), faq('What will the monthly report show?', 'Reports cover completed work, search performance observations and recommended next steps. Analytics and search-tool access are agreed during onboarding.'), faq('Does the fee include new content?', 'Content recommendations are included. Writing new content is included only where the agreed monthly scope explicitly covers it.')],
  },
  {
    slug: 'google-business-profile', title: 'Google Business Profile', category: 'Local Visibility', headline: 'Get Found by Local Customers on Google Search and Maps', description: 'Present accurate business information, organise your profile and build a practical approach to ongoing local visibility.', startingPrice: 'Setup from £149 one-time · management from £129/month',
    offers: ['Profile setup', 'Profile optimisation', 'Monthly management'], included: ['Business profile audit', 'Profile setup and configuration', 'Business category selection', 'Service area configuration', 'Business information optimisation', 'Products and services optimisation where supported', 'Photo and content recommendations', 'Review response guidance', 'Profile performance reporting', 'Local visibility improvement recommendations'],
    packages: [pack('setup', 'GBP Setup', 'From £149 one-time', "3–5 working days, excluding Google's verification delays", 'Support setting up an accurate profile for an eligible business.', 'Eligible businesses creating their first profile.', ['Eligibility and business information review', 'Profile setup and category selection', 'Service area configuration where appropriate', 'Verification process guidance']), pack('optimisation', 'GBP Optimisation', 'From £199 one-time', '5–7 working days', 'Review and improve an existing business profile.', 'Businesses with a profile needing a clearer presentation.', ['Profile audit and information optimisation', 'Category, product and service review where supported', 'Photo and content recommendations', 'Review response guidance', 'Local visibility recommendations']), pack('management', 'GBP Monthly Management', 'From £129/month', 'Ongoing', 'Maintain accurate information and review profile activity.', 'Businesses wanting continuing profile support.', ['Agreed profile updates', 'Content and review response guidance', 'Profile performance reporting', 'Local visibility recommendations', 'Regular information checks'])],
    note: 'Google Business Profile itself is free. Optitech charges for professional setup, optimisation and management. Google controls eligibility, verification and rankings; verification and top Google Maps positions are not guaranteed. We follow Google’s eligibility and management guidelines, use accurate business details and never create fake reviews or inaccurate locations.',
    faqs: [faq('Is Google Business Profile free?', 'Yes. Our fees cover professional setup, optimisation and ongoing management, not access to Google Business Profile itself.'), faq('Can you guarantee verification?', 'No. Google determines verification methods and outcomes. The setup estimate excludes Google’s verification delays.'), faq('Will my business appear at the top of Google Maps?', 'We cannot guarantee positions. We improve profile accuracy and presentation and provide local visibility recommendations.'), faq('Do I need a shop open to customers?', 'Eligibility depends on how your business serves customers. We check Google’s current guidelines and configure addresses or service areas accurately.'), faq('Can you help with customer reviews?', 'We guide professional responses and genuine review practices. We do not create fake reviews or manipulate feedback.')],
  },
  {
    slug: 'digital-advertising', title: 'Digital Advertising', category: 'Paid Campaigns', headline: 'Reach the Right Audience. Make Every Campaign Count.', description: 'Plan and manage paid campaigns around your audience, budget and business goals, with transparent reporting and ongoing optimisation.', startingPrice: 'From £350/month + advertising spend',
    offers: ['Google Ads', 'Meta Ads', 'Multi-channel advertising'], included: ['Campaign planning', 'Audience and keyword research', 'Conversion tracking', 'Ad creative coordination', 'Campaign setup', 'Bid and budget optimisation', 'Landing page recommendations', 'Performance reporting'],
    packages: [pack('google-ads', 'Google Ads Management', '£350–£650/month + advertising spend', 'Ongoing; setup schedule agreed during onboarding', 'Manage search campaigns around relevant customer intent.', 'Businesses reaching customers through Google Ads.', ['Campaign planning and keyword research', 'Campaign setup', 'Conversion tracking where supported', 'Bid and budget optimisation', 'Landing page recommendations and reporting']), pack('meta-ads', 'Meta Ads Management', '£350–£650/month + advertising spend', 'Ongoing; setup schedule agreed during onboarding', 'Manage audience-led campaigns on Meta platforms.', 'Businesses promoting products or services on Facebook and Instagram.', ['Audience research and campaign planning', 'Ad creative coordination', 'Campaign setup and tracking where supported', 'Budget optimisation', 'Performance reporting']), pack('multi-channel', 'Multi-Channel Advertising', 'Custom Quote', 'Based on channel mix and scope', 'Coordinate campaigns across agreed channels.', 'Businesses with a broader campaign scope.', ['Channel and budget planning', 'Coordinated campaign setup', 'Tracking plan', 'Creative and landing page recommendations', 'Agreed reporting and optimisation schedule'])],
    note: 'Advertising spend is separate from management fees and is paid to the advertising platform. Creative production and additional tools are included only where stated in the quotation. Leads, revenue and return on advertising spend are not guaranteed.',
    faqs: [faq('Is advertising spend included?', 'No. Advertising spend is separate from management fees. We agree the platform budget with you before launching.'), faq('Which channel should I use?', 'We review your audience, offer, customer journey and budget before recommending Google Ads, Meta Ads or a combination.'), faq('Do you guarantee leads or sales?', 'No. Results depend on market conditions, your offer, budget and website. We report and optimise without guaranteeing leads, revenue or return.'), faq('Who produces the adverts?', 'We coordinate creative requirements. Copy, photography, video and other production are scoped in your quotation.'), faq('Can you track enquiries and purchases?', 'We plan tracking where supported, reviewing access, consent settings and technical requirements during onboarding.')],
  },
  {
    slug: 'ai-automation', title: 'AI & Business Automation', category: 'Smart Workflows', headline: 'Automate Repetitive Work. Focus on Growing Your Business.', description: 'Connect your tools and simplify repeatable tasks with practical automation, clear safeguards and human oversight where it matters.', startingPrice: 'From £350 setup',
    offers: ['CRM and lead automation', 'Business workflow automation', 'AI assistants and chatbots', 'Third-party integrations'], included: ['Website chatbots', 'Lead capture and routing', 'Automated email follow-ups', 'CRM integrations', 'Customer support workflows', 'Appointment automation', 'Internal process automation', 'AI-powered knowledge assistants', 'Third-party API integrations'],
    packages: [pack('crm-starter', 'CRM Automation Starter', '£350–£750 setup', '3–10 working days', 'Connect a defined lead journey to your CRM.', 'Small teams improving lead handling and follow-up.', ['Lead capture and routing plan', 'Scoped CRM integration', 'Agreed follow-up workflow', 'Testing and handover', 'Human review and exception handling']), pack('workflow', 'Business Workflow Automation', 'From £750', '1–3 weeks', 'Connect tools and automate a defined business process.', 'Businesses reducing repetitive internal tasks.', ['Workflow discovery and mapping', 'Scoped platform and API connections', 'Appointment or internal process automation', 'Error handling and review points', 'Testing and documentation']), pack('advanced-ai', 'Advanced AI Automation', 'Custom Quote', 'Based on scope', 'A tailored AI-assisted solution with appropriate safeguards.', 'Teams requiring assistants or complex automation.', ['Requirements and data-access review', 'Scoped chatbot or knowledge assistant', 'Agreed system integrations', 'Human oversight and escalation design', 'Evaluation, testing and handover'])],
    note: 'External AI/API usage, automation platform subscriptions and ongoing support may incur separate costs. We agree data access, privacy requirements, permissions, retention and human review points before implementation. AI output should be reviewed before consequential decisions or external use.',
    faqs: [faq('What should we automate first?', 'Start with a repetitive, defined process such as lead routing or appointments. Discovery identifies a manageable workflow and suitable review points.'), faq('Will this work with our CRM?', 'We review APIs and integrations before quoting. Platform access, licences and technical limitations determine what can be connected.'), faq('Are AI and platform fees included?', 'External AI/API usage and platform subscriptions are separate unless explicitly included. Ongoing support is scoped separately.'), faq('How is business data handled?', 'We agree required data, permissions, third-party access, retention and privacy requirements during discovery. Sensitive information is used only through approved workflows.'), faq('Can AI operate without human review?', 'We define review and escalation points for the workflow. AI can be inaccurate; consequential decisions and external communications need suitable human oversight.')],
  },
  {
    slug: 'custom-software', title: 'Custom Software Development', category: 'Tailored Systems', headline: 'Custom Software Built Around Your Business', description: 'Turn specific operational requirements into useful software, with a clear scope, considered architecture and a practical delivery plan.', startingPrice: 'From £2,500',
    offers: ['Custom web applications', 'Business dashboards and portals', 'SaaS and MVP development', 'API and system integrations'], included: ['Requirement analysis', 'UI/UX planning', 'Frontend development', 'Backend development', 'Database architecture', 'Authentication and permissions', 'API integration', 'Testing', 'Deployment', 'Documentation'],
    packages: [pack('web-app', 'Custom Web Applications', 'From £2,500', '4–8+ weeks', 'An application built around your business workflow.', 'Businesses needing functionality beyond a standard website.', ['Requirement analysis and UI/UX planning', 'Frontend and backend development', 'Database architecture', 'Authentication and permissions where scoped', 'Testing, deployment and documentation']), pack('dashboard', 'Business Dashboards & Portals', 'Custom Quote', 'Broad estimate agreed after discovery', 'Give teams or customers useful information and tools.', 'Businesses managing data, reporting or customer access.', ['Data and workflow discovery', 'Dashboard or portal interface', 'Role-based access where scoped', 'System integrations', 'Testing and documentation']), pack('saas-mvp', 'SaaS / MVP Development', 'Custom Quote', 'Broad estimate agreed after discovery', 'Build a focused first version of your software product.', 'Founders and teams validating a product idea.', ['MVP scope and priorities', 'UI/UX and architecture planning', 'Agreed product functionality', 'Testing and deployment', 'Technical handover']), pack('integrations', 'API & System Integrations', 'Custom Quote', 'Broad estimate agreed after discovery', 'Connect systems through agreed interfaces and data flows.', 'Businesses connecting existing tools.', ['API and data requirements analysis', 'Integration development', 'Authentication and permission planning', 'Error handling and testing', 'Deployment and documentation'])],
    note: 'Timelines are broad estimates only. Final pricing depends on functionality, integrations, data requirements and complexity. Hosting, third-party licences, external API usage and ongoing support are agreed separately.',
    faqs: [faq('What do you need for a quote?', 'Tell us who will use the software, the problems it must solve, required features, integrations, data and deadlines. Discovery turns this into an agreed scope.'), faq('How does an application differ from a website?', 'A website mainly presents content. Applications support authenticated accounts, data processing or business workflows that need a separate software scope.'), faq('Can you build an MVP first?', 'Yes. We prioritise a focused feature set, agree what is outside the first release and plan further development separately.'), faq('How accurate is the delivery estimate?', '4–8+ weeks is a broad starting estimate for a scoped web application. Integrations, testing, data and functionality can extend it. Discovery informs the schedule.'), faq('Is ongoing support included?', 'Development includes agreed deployment and documentation. Hosting, maintenance, third-party fees and support are specified separately.')],
  },
  {
    slug: 'website-maintenance', title: 'Website Maintenance & Support', category: 'Ongoing Support', headline: 'Keep Your Website Secure, Updated and Performing', description: 'Give your website regular attention with defined maintenance tasks, practical support allowances and clear response expectations.', startingPrice: 'From £49/month',
    offers: ['Routine website care', 'Content and technical support', 'Performance checks'], included: ['Routine updates for the agreed platform', 'Scheduled backups and security checks', 'Uptime monitoring', 'Basic technical support', 'Small content updates within plan allowances', 'Performance checks', 'Clear support scope and response expectations'],
    packages: [pack('essential', 'Essential Care', '£49/month', 'Ongoing; onboarding after access review', 'Regular care for a straightforward website.', 'Small websites needing routine maintenance.', ['Monthly routine update checks', 'Weekly backups; 4-week retention where supported', 'Security and uptime monitoring', 'Up to 30 minutes of technical support per month', 'Quarterly performance checks', 'Target initial response: within 3 working days']), pack('business', 'Business Care', '£99/month', 'Ongoing; onboarding after access review', 'Routine care with a small content-change allowance.', 'Businesses updating website content regularly.', ['Fortnightly routine update checks', 'Daily backups; 4-week retention where supported', 'Security and uptime monitoring', 'Up to 1 hour of technical support and small content updates per month', 'Monthly performance checks', 'Target initial response: within 2 working days']), pack('priority', 'Priority Care', '£149/month', 'Ongoing; onboarding after access review', 'More frequent checks and a larger support allowance.', 'Businesses needing additional routine support.', ['Weekly routine update checks', 'Daily backups; 4-week retention where supported', 'Security and uptime monitoring', 'Up to 2 hours of technical support and small content updates per month', 'Monthly performance checks', 'Target initial response: within 1 working day'])],
    note: 'Plan allowances are proposed monthly scopes, confirmed after reviewing your platform and access. Unused time does not roll over. New features, redesigns, major incidents and third-party costs are quoted separately. Response targets apply Monday–Friday, excluding UK bank holidays; they are initial acknowledgement targets, not resolution guarantees or a contractual SLA. No guaranteed uptime or instant support is promised.',
    comparison: { caption: 'Compare monthly care plans', headings: ['Maintenance task', 'Essential · £49/month', 'Business · £99/month', 'Priority · £149/month'], rows: [
      ['Routine update checks', 'Monthly', 'Fortnightly', 'Weekly'], ['Backups (where supported)', 'Weekly; 4-week retention', 'Daily; 4-week retention', 'Daily; 4-week retention'], ['Security monitoring', 'Included', 'Included', 'Included'], ['Uptime monitoring', 'Included', 'Included', 'Included'], ['Basic technical support', '30 minutes/month', 'Shared 1 hour/month', 'Shared 2 hours/month'], ['Small content updates', 'Quoted separately', 'Within shared allowance', 'Within shared allowance'], ['Performance checks', 'Quarterly', 'Monthly', 'Monthly'], ['Target initial response', '3 working days', '2 working days', '1 working day'],
    ] },
    faqs: [faq('Is support unlimited?', 'No. Essential includes up to 30 minutes of technical support each month. Business and Priority provide shared allowances of 1 or 2 hours for support and small content updates. Unused time does not roll over.'), faq('What counts as a small content update?', 'Changes to existing text or images on existing pages. New pages, features, redesigns and substantial changes need a separate quotation.'), faq('Do you guarantee uptime or instant fixes?', 'No. Monitoring identifies issues, but there is no guaranteed uptime or instant support. Targets cover initial acknowledgement during working days, not guaranteed resolution.'), faq('Can you maintain a website built by someone else?', 'We review the platform, access, hosting and condition first. Remedial work may be quoted separately before a care plan begins.'), faq('Are hosting and licences included?', 'Hosting, plugins, licences and third-party charges are separate unless included in the quotation. Backup schedules depend on platform support and access.')],
  },
];
const processes = {
  seo: ['Discovery', 'Audit & planning', 'Optimisation', 'Performance review', 'Reporting & next steps'],
  'google-business-profile': ['Discovery & eligibility', 'Profile audit & planning', 'Setup / optimisation', 'Accuracy review', 'Handover / management'],
  'digital-advertising': ['Discovery', 'Campaign planning', 'Setup & implementation', 'Tracking & creative review', 'Launch & optimisation'],
  'ai-automation': ['Discovery', 'Workflow & safeguards planning', 'Implementation', 'Testing & human review', 'Delivery & handover'],
  'website-maintenance': ['Access & condition review', 'Care planning', 'Routine maintenance', 'Checks & issue review', 'Reporting & ongoing support'],
};
for (const service of services) {
  service.process = processes[service.slug] || ['Discovery', 'Planning', 'Development / implementation', 'Review & testing', 'Delivery / launch'];
  service.seoTitle = `${service.title} UK | Optitech`;
}
export const findService = slug => services.find(service => service.slug === slug);
export const quoteHref = (service, packageId) => `/contact/quote?${new URLSearchParams({ service: service.slug, ...(packageId ? { package: packageId } : {}) })}`;
export const finalCta = { headline: "Let's Build Something That Works for Your Business", description: "Tell us what you need, and we'll recommend the right solution for your goals and budget.", button: 'Get Your Free Quote' };

// Existing service descriptions must not contradict the new package catalogue.
// These replacements have equal byte lengths, preserving archived Flight text lengths.
const firstPrice = price => price.match(/£[\d,]+/)[0];
export const archivedPriceReplacements = [
  ['£750', firstPrice(findService('web-development').packages.find(item => item.id === 'small-business').price)],
  ['£1,200', firstPrice(findService('ecommerce').packages[0].price)],
  ['£450/month', findService('seo').packages[0].price],
  ['£500/month', `${firstPrice(findService('digital-advertising').packages[0].price)}/month`],
];
